-- Enable Row Level Security on all tables.
-- MindShed connects via Prisma (postgres role, bypasses RLS).
-- This blocks access via Supabase PostgREST and silences RLS warnings.

ALTER TABLE hobby ENABLE ROW LEVEL SECURITY;
ALTER TABLE project ENABLE ROW LEVEL SECURITY;
ALTER TABLE step ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_note ENABLE ROW LEVEL SECURITY;
ALTER TABLE blocker ENABLE ROW LEVEL SECURITY;
ALTER TABLE idea ENABLE ROW LEVEL SECURITY;
ALTER TABLE inventory_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE bom_item ENABLE ROW LEVEL SECURITY;
ALTER TABLE step_image ENABLE ROW LEVEL SECURITY;
ALTER TABLE reminder ENABLE ROW LEVEL SECURITY;
ALTER TABLE setting ENABLE ROW LEVEL SECURITY;
